## Virtual Service
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: production-redirect-id-to-com
  namespace: production
spec:
  hosts:
  - abdidarmawan.id
  gateways:
  - gateway
  http:
  - match:
    - uri:
        exact: /
    redirect:
      uri: /
      authority: abdidarmawan.com
